name: Build cf.gov Docker images

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: cfpb/actions/docker-build-push@1be1a44a38e05b7092c844511a0d214e93b43c21
        with:
          image-name: cfgov
          token: ${{ secrets.GITHUB_TOKEN }}
