name: Build cf.gov Docker images

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: cfpb/actions/docker-build-push@2df4207b96f87a3c424ab7e4fa4d368889d1c92f
        with:
          image-name: cfgov
