name: Build cf.gov Docker images

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: cfpb/actions/docker-build-push@f584bc1041a1c0590d35533f4f3478ad1229f210
        with:
          image-name: cfgov
